spring:
  application:
    name: ms-users

  datasource:
    url: ${MS_USERS_DB_URL:jdbc:postgresql://localhost:5432/dbusers}
    username: ${MS_USERS_DB_USERNAME:postgres}
    password: ${MS_USERS_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

server:
  port: ${MS_USERS_PORT:8084}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

app:
  jwt:
    secret: ${MS_USERS_JWT_SECRET:mySecretKeyForJWTGenerationWithAtLeast32Characters}
    expiration: ${MS_USERS_JWT_EXPIRATION:86400000}
  seed:
    admin:
      enabled: ${MS_USERS_ADMIN_SEED_ENABLED:true}
      name: ${MS_USERS_ADMIN_NAME:Admin Principal}
      email: ${MS_USERS_ADMIN_EMAIL:admin@transportes.local}
      password: ${MS_USERS_ADMIN_PASSWORD:Admin123!}

logging:
  level:
    com.core.msusers: DEBUG
